== NAME

Set::CSS - set of CSS classes

== VERSION

version 0.0.1

== SYNOPSIS

....
use Set::CSS ();

my $set = Set::CSS->new( "class1", );
$set->insert("blast");

# Prints ' class="blast class1"'
print $set->as_html(), "\n";
....

== DESCRIPTION

Inheriting from https://metacpan.org/pod/Set%3A%3AObject[Set::Object]
this class provides methods for emitting HTML.

If $args\{on_empty} is not true *and* the set is empty, then no output
shall be emitted.

== METHODS

=== $self->html_attrs(\%args)

Returns a hash reference of HTML attributes.

=== $self->as_html(\%args)

Returns a string of HTML attributes.

== Media Recommendations

https://www.youtube.com/watch?v=4hjgkvuKES8[Hallelujah - Cover by Lucy
Thomas]

== SEE ALSO

https://metacpan.org/pod/Set%3A%3AObject[Set::Object] - Set::CSS
inherits its methods

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/class[HTML’s
`class' attribute]

https://api.jquery.com/category/manipulation/class-attribute/[jQuery
class methods]

== SUPPORT

=== Websites

The following websites have more information about this module, and may
be of help to you. As always, in addition to those websites please use
your favorite search engine to discover more resources.

* MetaCPAN
+
A modern, open-source CPAN search engine, useful to view POD in HTML
format.
+
https://metacpan.org/release/Set-CSS
* RT: CPAN’s Bug Tracker
+
The RT ( Request Tracker ) website is the default bug/issue tracking
system for CPAN.
+
https://rt.cpan.org/Public/Dist/Display.html?Name=Set-CSS
* CPANTS
+
The CPANTS is a website that analyzes the Kwalitee ( code metrics ) of a
distribution.
+
http://cpants.cpanauthors.org/dist/Set-CSS
* CPAN Testers
+
The CPAN Testers is a network of smoke testers who run automated tests
on uploaded CPAN distributions.
+
http://www.cpantesters.org/distro/S/Set-CSS
* CPAN Testers Matrix
+
The CPAN Testers Matrix is a website that provides a visual overview of
the test results for a distribution on various Perls/platforms.
+
http://matrix.cpantesters.org/?dist=Set-CSS
* CPAN Testers Dependencies
+
The CPAN Testers Dependencies is a website that shows a chart of the
test results of all dependencies for a distribution.
+
http://deps.cpantesters.org/?module=Set::CSS

=== Bugs / Feature Requests

Please report any bugs or feature requests by email to
`bug-set-css at rt.cpan.org`, or through the web interface at
https://rt.cpan.org/Public/Bug/Report.html?Queue=Set-CSS. You will be
automatically notified of any progress on the request by the system.

=== Source Code

The code is open to the world, and available for you to hack on. Please
feel free to browse it and play with it, or whatever. If you want to
contribute patches, please send me a diff or prod me to pull from your
repository :)

https://github.com/shlomif/Set-CSS

....
git clone git://github.com/shlomif/Set-CSS.git
....

== AUTHOR

Shlomi Fish shlomif@cpan.org

== BUGS

Please report any bugs or feature requests on the bugtracker website
https://github.com/shlomif/Set-CSS/issues

When submitting a bug or request, please include a test-file or a patch
to an existing test-file that illustrates the bug or desired feature.

== COPYRIGHT AND LICENSE

This software is Copyright (c) 2021 by Shlomi Fish.

This is free software, licensed under:

....
The MIT (X11) License
....
